updated pushover stuff

diff --git a/resources/configure/default/home/bin/pnote b/resources/configure/default/home/bin/pnote
--- a/resources/configure/default/home/bin/pnote
+++ b/resources/configure/default/home/bin/pnote
@@ -6,23 +6,13 @@ if [[ -z $1 ]]; then
 fi
 MESSAGE="$@"
 
-APP_PASS=pushover/pnote
-USER_PASS=pushover/user
-
-if ! hash pass >& /dev/null ; then
-    echo "'pass' not installed. Please install and configure $APP_PASS and $USER_PASS"
-    exit 1
+if ! [ $PUSHOVER_USER_TOK ]; then
+    . $HOME/.pushover || { echo "$HOME/.pushover not found"; exit 1; }
 fi
 
-pass show --clip $APP_PASS || exit 1
-PNOTE_TOK=$(xclip -o -selection clipboard)
-
-pass show --clip $USER_PASS || exit 1
-PO_USER_TOK=$(xclip -o -selection clipboard)
-
 curl -s \
-    -F "token=$PNOTE_TOK" \
-    -F "user=$PO_USER_TOK" \
+    -F "token=$PUSHOVER_APP_TOK" \
+    -F "user=$PUSHOVER_USER_TOK" \
     -F "message=$MESSAGE" \
     -F "title=$HOSTNAME" \
     https://api.pushover.net/1/messages > /dev/null
